build-and-test code

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -64,4 +64,34 @@ jobs:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
         with:
           args: --sarif-file-output=snyk.sarif
-  
+  build_and_test:
+    runs-on: ubuntu-latest
+    needs: compile
+    steps:
+    - uses: actions/checkout@v2
+    - uses: actions/cache@v2
+      with:
+        path: ~/.m2/repository
+        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
+        restore-keys: |
+          ${{ runner.os }}-maven-
+    - name: Set up JDK 14
+      uses: actions/setup-java@v1
+      with:
+        java-version: 14
+    - name: Check working directory
+      run: echo "${GITHUB_WORKSPACE}"
+    - name: Build project with Maven
+      run: | 
+           mvn -B package --file pom.xml
+           mkdir staging && cp target/*.jar staging/ 
+    - name: Test
+      run: mvn --batch-mode -Dmaven.test.failure.ignore=true test
+    - name: Test Report
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: JEST Tests            # Name of the check run which will be created
+        path: target/surefire-reports/TEST-*.xml    # Path to test results
+        reporter: java-junit       # Format of test results
+        fail-on-error: 'false'
